const  githubResult = """
{
"total_count": 33402,
"incomplete_results": false,
"items": [
{
"login": "matheus",
"id": 3068278,
"node_id": "MDQ6VXNlcjMwNjgyNzg=",
"avatar_url": "https://avatars.githubusercontent.com/u/3068278?v=4",
"gravatar_id": "",
"url": "https://api.github.com/users/matheus",
"html_url": "https://github.com/matheus",
"followers_url": "https://api.github.com/users/matheus/followers",
"following_url": "https://api.github.com/users/matheus/following{/other_user}",
"gists_url": "https://api.github.com/users/matheus/gists{/gist_id}",
"starred_url": "https://api.github.com/users/matheus/starred{/owner}{/repo}",
"subscriptions_url": "https://api.github.com/users/matheus/subscriptions",
"organizations_url": "https://api.github.com/users/matheus/orgs",
"repos_url": "https://api.github.com/users/matheus/repos",
"events_url": "https://api.github.com/users/matheus/events{/privacy}",
"received_events_url": "https://api.github.com/users/matheus/received_events",
"type": "User",
"site_admin": false,
"score": 1
},
{
"login": "matheusbattisti",
"id": 11837941,
"node_id": "MDQ6VXNlcjExODM3OTQx",
"avatar_url": "https://avatars.githubusercontent.com/u/11837941?v=4",
"gravatar_id": "",
"url": "https://api.github.com/users/matheusbattisti",
"html_url": "https://github.com/matheusbattisti",
"followers_url": "https://api.github.com/users/matheusbattisti/followers",
"following_url": "https://api.github.com/users/matheusbattisti/following{/other_user}",
"gists_url": "https://api.github.com/users/matheusbattisti/gists{/gist_id}",
"starred_url": "https://api.github.com/users/matheusbattisti/starred{/owner}{/repo}",
"subscriptions_url": "https://api.github.com/users/matheusbattisti/subscriptions",
"organizations_url": "https://api.github.com/users/matheusbattisti/orgs",
"repos_url": "https://api.github.com/users/matheusbattisti/repos",
"events_url": "https://api.github.com/users/matheusbattisti/events{/privacy}",
"received_events_url": "https://api.github.com/users/matheusbattisti/received_events",
"type": "User",
"site_admin": false,
"score": 1
},
{
"login": "matheuss",
"id": 4721750,
"node_id": "MDQ6VXNlcjQ3MjE3NTA=",
"avatar_url": "https://avatars.githubusercontent.com/u/4721750?v=4",
"gravatar_id": "",
"url": "https://api.github.com/users/matheuss",
"html_url": "https://github.com/matheuss",
"followers_url": "https://api.github.com/users/matheuss/followers",
"following_url": "https://api.github.com/users/matheuss/following{/other_user}",
"gists_url": "https://api.github.com/users/matheuss/gists{/gist_id}",
"starred_url": "https://api.github.com/users/matheuss/starred{/owner}{/repo}",
"subscriptions_url": "https://api.github.com/users/matheuss/subscriptions",
"organizations_url": "https://api.github.com/users/matheuss/orgs",
"repos_url": "https://api.github.com/users/matheuss/repos",
"events_url": "https://api.github.com/users/matheuss/events{/privacy}",
"received_events_url": "https://api.github.com/users/matheuss/received_events",
"type": "User",
"site_admin": false,
"score": 1
},
{
"login": "embs",
"id": 1200033,
"node_id": "MDQ6VXNlcjEyMDAwMzM=",
"avatar_url": "https://avatars.githubusercontent.com/u/1200033?v=4",
"gravatar_id": "",
"url": "https://api.github.com/users/embs",
"html_url": "https://github.com/embs",
"followers_url": "https://api.github.com/users/embs/followers",
"following_url": "https://api.github.com/users/embs/following{/other_user}",
"gists_url": "https://api.github.com/users/embs/gists{/gist_id}",
"starred_url": "https://api.github.com/users/embs/starred{/owner}{/repo}",
"subscriptions_url": "https://api.github.com/users/embs/subscriptions",
"organizations_url": "https://api.github.com/users/embs/orgs",
"repos_url": "https://api.github.com/users/embs/repos",
"events_url": "https://api.github.com/users/embs/events{/privacy}",
"received_events_url": "https://api.github.com/users/embs/received_events",
"type": "User",
"site_admin": false,
"score": 1
},
{
"login": "matheusml",
"id": 444202,
"node_id": "MDQ6VXNlcjQ0NDIwMg==",
"avatar_url": "https://avatars.githubusercontent.com/u/444202?v=4",
"gravatar_id": "",
"url": "https://api.github.com/users/matheusml",
"html_url": "https://github.com/matheusml",
"followers_url": "https://api.github.com/users/matheusml/followers",
"following_url": "https://api.github.com/users/matheusml/following{/other_user}",
"gists_url": "https://api.github.com/users/matheusml/gists{/gist_id}",
"starred_url": "https://api.github.com/users/matheusml/starred{/owner}{/repo}",
"subscriptions_url": "https://api.github.com/users/matheusml/subscriptions",
"organizations_url": "https://api.github.com/users/matheusml/orgs",
"repos_url": "https://api.github.com/users/matheusml/repos",
"events_url": "https://api.github.com/users/matheusml/events{/privacy}",
"received_events_url": "https://api.github.com/users/matheusml/received_events",
"type": "User",
"site_admin": false,
"score": 1
},
{
"login": "matheuspython",
"id": 64442354,
"node_id": "MDQ6VXNlcjY0NDQyMzU0",
"avatar_url": "https://avatars.githubusercontent.com/u/64442354?v=4",
"gravatar_id": "",
"url": "https://api.github.com/users/matheuspython",
"html_url": "https://github.com/matheuspython",
"followers_url": "https://api.github.com/users/matheuspython/followers",
"following_url": "https://api.github.com/users/matheuspython/following{/other_user}",
"gists_url": "https://api.github.com/users/matheuspython/gists{/gist_id}",
"starred_url": "https://api.github.com/users/matheuspython/starred{/owner}{/repo}",
"subscriptions_url": "https://api.github.com/users/matheuspython/subscriptions",
"organizations_url": "https://api.github.com/users/matheuspython/orgs",
"repos_url": "https://api.github.com/users/matheuspython/repos",
"events_url": "https://api.github.com/users/matheuspython/events{/privacy}",
"received_events_url": "https://api.github.com/users/matheuspython/received_events",
"type": "User",
"site_admin": false,
"score": 1
},
{
"login": "cardoso",
"id": 5606812,
"node_id": "MDQ6VXNlcjU2MDY4MTI=",
"avatar_url": "https://avatars.githubusercontent.com/u/5606812?v=4",
"gravatar_id": "",
"url": "https://api.github.com/users/cardoso",
"html_url": "https://github.com/cardoso",
"followers_url": "https://api.github.com/users/cardoso/followers",
"following_url": "https://api.github.com/users/cardoso/following{/other_user}",
"gists_url": "https://api.github.com/users/cardoso/gists{/gist_id}",
"starred_url": "https://api.github.com/users/cardoso/starred{/owner}{/repo}",
"subscriptions_url": "https://api.github.com/users/cardoso/subscriptions",
"organizations_url": "https://api.github.com/users/cardoso/orgs",
"repos_url": "https://api.github.com/users/cardoso/repos",
"events_url": "https://api.github.com/users/cardoso/events{/privacy}",
"received_events_url": "https://api.github.com/users/cardoso/received_events",
"type": "User",
"site_admin": false,
"score": 1
},
{
"login": "onhernandes",
"id": 12698656,
"node_id": "MDQ6VXNlcjEyNjk4NjU2",
"avatar_url": "https://avatars.githubusercontent.com/u/12698656?v=4",
"gravatar_id": "",
"url": "https://api.github.com/users/onhernandes",
"html_url": "https://github.com/onhernandes",
"followers_url": "https://api.github.com/users/onhernandes/followers",
"following_url": "https://api.github.com/users/onhernandes/following{/other_user}",
"gists_url": "https://api.github.com/users/onhernandes/gists{/gist_id}",
"starred_url": "https://api.github.com/users/onhernandes/starred{/owner}{/repo}",
"subscriptions_url": "https://api.github.com/users/onhernandes/subscriptions",
"organizations_url": "https://api.github.com/users/onhernandes/orgs",
"repos_url": "https://api.github.com/users/onhernandes/repos",
"events_url": "https://api.github.com/users/onhernandes/events{/privacy}",
"received_events_url": "https://api.github.com/users/onhernandes/received_events",
"type": "User",
"site_admin": false,
"score": 1
},
{
"login": "matheusfacure",
"id": 18542597,
"node_id": "MDQ6VXNlcjE4NTQyNTk3",
"avatar_url": "https://avatars.githubusercontent.com/u/18542597?v=4",
"gravatar_id": "",
"url": "https://api.github.com/users/matheusfacure",
"html_url": "https://github.com/matheusfacure",
"followers_url": "https://api.github.com/users/matheusfacure/followers",
"following_url": "https://api.github.com/users/matheusfacure/following{/other_user}",
"gists_url": "https://api.github.com/users/matheusfacure/gists{/gist_id}",
"starred_url": "https://api.github.com/users/matheusfacure/starred{/owner}{/repo}",
"subscriptions_url": "https://api.github.com/users/matheusfacure/subscriptions",
"organizations_url": "https://api.github.com/users/matheusfacure/orgs",
"repos_url": "https://api.github.com/users/matheusfacure/repos",
"events_url": "https://api.github.com/users/matheusfacure/events{/privacy}",
"received_events_url": "https://api.github.com/users/matheusfacure/received_events",
"type": "User",
"site_admin": false,
"score": 1
},
{
"login": "MatheusAlvarez",
"id": 88752578,
"node_id": "MDQ6VXNlcjg4NzUyNTc4",
"avatar_url": "https://avatars.githubusercontent.com/u/88752578?v=4",
"gravatar_id": "",
"url": "https://api.github.com/users/MatheusAlvarez",
"html_url": "https://github.com/MatheusAlvarez",
"followers_url": "https://api.github.com/users/MatheusAlvarez/followers",
"following_url": "https://api.github.com/users/MatheusAlvarez/following{/other_user}",
"gists_url": "https://api.github.com/users/MatheusAlvarez/gists{/gist_id}",
"starred_url": "https://api.github.com/users/MatheusAlvarez/starred{/owner}{/repo}",
"subscriptions_url": "https://api.github.com/users/MatheusAlvarez/subscriptions",
"organizations_url": "https://api.github.com/users/MatheusAlvarez/orgs",
"repos_url": "https://api.github.com/users/MatheusAlvarez/repos",
"events_url": "https://api.github.com/users/MatheusAlvarez/events{/privacy}",
"received_events_url": "https://api.github.com/users/MatheusAlvarez/received_events",
"type": "User",
"site_admin": false,
"score": 1
},
{
"login": "matheusfelipeog",
"id": 50463866,
"node_id": "MDQ6VXNlcjUwNDYzODY2",
"avatar_url": "https://avatars.githubusercontent.com/u/50463866?v=4",
"gravatar_id": "",
"url": "https://api.github.com/users/matheusfelipeog",
"html_url": "https://github.com/matheusfelipeog",
"followers_url": "https://api.github.com/users/matheusfelipeog/followers",
"following_url": "https://api.github.com/users/matheusfelipeog/following{/other_user}",
"gists_url": "https://api.github.com/users/matheusfelipeog/gists{/gist_id}",
"starred_url": "https://api.github.com/users/matheusfelipeog/starred{/owner}{/repo}",
"subscriptions_url": "https://api.github.com/users/matheusfelipeog/subscriptions",
"organizations_url": "https://api.github.com/users/matheusfelipeog/orgs",
"repos_url": "https://api.github.com/users/matheusfelipeog/repos",
"events_url": "https://api.github.com/users/matheusfelipeog/events{/privacy}",
"received_events_url": "https://api.github.com/users/matheusfelipeog/received_events",
"type": "User",
"site_admin": false,
"score": 1
},
{
"login": "matheusgr",
"id": 882438,
"node_id": "MDQ6VXNlcjg4MjQzOA==",
"avatar_url": "https://avatars.githubusercontent.com/u/882438?v=4",
"gravatar_id": "",
"url": "https://api.github.com/users/matheusgr",
"html_url": "https://github.com/matheusgr",
"followers_url": "https://api.github.com/users/matheusgr/followers",
"following_url": "https://api.github.com/users/matheusgr/following{/other_user}",
"gists_url": "https://api.github.com/users/matheusgr/gists{/gist_id}",
"starred_url": "https://api.github.com/users/matheusgr/starred{/owner}{/repo}",
"subscriptions_url": "https://api.github.com/users/matheusgr/subscriptions",
"organizations_url": "https://api.github.com/users/matheusgr/orgs",
"repos_url": "https://api.github.com/users/matheusgr/repos",
"events_url": "https://api.github.com/users/matheusgr/events{/privacy}",
"received_events_url": "https://api.github.com/users/matheusgr/received_events",
"type": "User",
"site_admin": false,
"score": 1
},
{
"login": "MatheusPires99",
"id": 49207932,
"node_id": "MDQ6VXNlcjQ5MjA3OTMy",
"avatar_url": "https://avatars.githubusercontent.com/u/49207932?v=4",
"gravatar_id": "",
"url": "https://api.github.com/users/MatheusPires99",
"html_url": "https://github.com/MatheusPires99",
"followers_url": "https://api.github.com/users/MatheusPires99/followers",
"following_url": "https://api.github.com/users/MatheusPires99/following{/other_user}",
"gists_url": "https://api.github.com/users/MatheusPires99/gists{/gist_id}",
"starred_url": "https://api.github.com/users/MatheusPires99/starred{/owner}{/repo}",
"subscriptions_url": "https://api.github.com/users/MatheusPires99/subscriptions",
"organizations_url": "https://api.github.com/users/MatheusPires99/orgs",
"repos_url": "https://api.github.com/users/MatheusPires99/repos",
"events_url": "https://api.github.com/users/MatheusPires99/events{/privacy}",
"received_events_url": "https://api.github.com/users/MatheusPires99/received_events",
"type": "User",
"site_admin": false,
"score": 1
},
{
"login": "matheus-mf",
"id": 22971725,
"node_id": "MDQ6VXNlcjIyOTcxNzI1",
"avatar_url": "https://avatars.githubusercontent.com/u/22971725?v=4",
"gravatar_id": "",
"url": "https://api.github.com/users/matheus-mf",
"html_url": "https://github.com/matheus-mf",
"followers_url": "https://api.github.com/users/matheus-mf/followers",
"following_url": "https://api.github.com/users/matheus-mf/following{/other_user}",
"gists_url": "https://api.github.com/users/matheus-mf/gists{/gist_id}",
"starred_url": "https://api.github.com/users/matheus-mf/starred{/owner}{/repo}",
"subscriptions_url": "https://api.github.com/users/matheus-mf/subscriptions",
"organizations_url": "https://api.github.com/users/matheus-mf/orgs",
"repos_url": "https://api.github.com/users/matheus-mf/repos",
"events_url": "https://api.github.com/users/matheus-mf/events{/privacy}",
"received_events_url": "https://api.github.com/users/matheus-mf/received_events",
"type": "User",
"site_admin": false,
"score": 1
},
{
"login": "MatheusFC2",
"id": 69259671,
"node_id": "MDQ6VXNlcjY5MjU5Njcx",
"avatar_url": "https://avatars.githubusercontent.com/u/69259671?v=4",
"gravatar_id": "",
"url": "https://api.github.com/users/MatheusFC2",
"html_url": "https://github.com/MatheusFC2",
"followers_url": "https://api.github.com/users/MatheusFC2/followers",
"following_url": "https://api.github.com/users/MatheusFC2/following{/other_user}",
"gists_url": "https://api.github.com/users/MatheusFC2/gists{/gist_id}",
"starred_url": "https://api.github.com/users/MatheusFC2/starred{/owner}{/repo}",
"subscriptions_url": "https://api.github.com/users/MatheusFC2/subscriptions",
"organizations_url": "https://api.github.com/users/MatheusFC2/orgs",
"repos_url": "https://api.github.com/users/MatheusFC2/repos",
"events_url": "https://api.github.com/users/MatheusFC2/events{/privacy}",
"received_events_url": "https://api.github.com/users/MatheusFC2/received_events",
"type": "User",
"site_admin": false,
"score": 1
},
{
"login": "MatheusEli",
"id": 31008177,
"node_id": "MDQ6VXNlcjMxMDA4MTc3",
"avatar_url": "https://avatars.githubusercontent.com/u/31008177?v=4",
"gravatar_id": "",
"url": "https://api.github.com/users/MatheusEli",
"html_url": "https://github.com/MatheusEli",
"followers_url": "https://api.github.com/users/MatheusEli/followers",
"following_url": "https://api.github.com/users/MatheusEli/following{/other_user}",
"gists_url": "https://api.github.com/users/MatheusEli/gists{/gist_id}",
"starred_url": "https://api.github.com/users/MatheusEli/starred{/owner}{/repo}",
"subscriptions_url": "https://api.github.com/users/MatheusEli/subscriptions",
"organizations_url": "https://api.github.com/users/MatheusEli/orgs",
"repos_url": "https://api.github.com/users/MatheusEli/repos",
"events_url": "https://api.github.com/users/MatheusEli/events{/privacy}",
"received_events_url": "https://api.github.com/users/MatheusEli/received_events",
"type": "User",
"site_admin": false,
"score": 1
},
{
"login": "microhobby",
"id": 2633321,
"node_id": "MDQ6VXNlcjI2MzMzMjE=",
"avatar_url": "https://avatars.githubusercontent.com/u/2633321?v=4",
"gravatar_id": "",
"url": "https://api.github.com/users/microhobby",
"html_url": "https://github.com/microhobby",
"followers_url": "https://api.github.com/users/microhobby/followers",
"following_url": "https://api.github.com/users/microhobby/following{/other_user}",
"gists_url": "https://api.github.com/users/microhobby/gists{/gist_id}",
"starred_url": "https://api.github.com/users/microhobby/starred{/owner}{/repo}",
"subscriptions_url": "https://api.github.com/users/microhobby/subscriptions",
"organizations_url": "https://api.github.com/users/microhobby/orgs",
"repos_url": "https://api.github.com/users/microhobby/repos",
"events_url": "https://api.github.com/users/microhobby/events{/privacy}",
"received_events_url": "https://api.github.com/users/microhobby/received_events",
"type": "User",
"site_admin": false,
"score": 1
},
{
"login": "matheus1lva",
"id": 831308,
"node_id": "MDQ6VXNlcjgzMTMwOA==",
"avatar_url": "https://avatars.githubusercontent.com/u/831308?v=4",
"gravatar_id": "",
"url": "https://api.github.com/users/matheus1lva",
"html_url": "https://github.com/matheus1lva",
"followers_url": "https://api.github.com/users/matheus1lva/followers",
"following_url": "https://api.github.com/users/matheus1lva/following{/other_user}",
"gists_url": "https://api.github.com/users/matheus1lva/gists{/gist_id}",
"starred_url": "https://api.github.com/users/matheus1lva/starred{/owner}{/repo}",
"subscriptions_url": "https://api.github.com/users/matheus1lva/subscriptions",
"organizations_url": "https://api.github.com/users/matheus1lva/orgs",
"repos_url": "https://api.github.com/users/matheus1lva/repos",
"events_url": "https://api.github.com/users/matheus1lva/events{/privacy}",
"received_events_url": "https://api.github.com/users/matheus1lva/received_events",
"type": "User",
"site_admin": false,
"score": 1
},
{
"login": "matheusfrancisco",
"id": 6428732,
"node_id": "MDQ6VXNlcjY0Mjg3MzI=",
"avatar_url": "https://avatars.githubusercontent.com/u/6428732?v=4",
"gravatar_id": "",
"url": "https://api.github.com/users/matheusfrancisco",
"html_url": "https://github.com/matheusfrancisco",
"followers_url": "https://api.github.com/users/matheusfrancisco/followers",
"following_url": "https://api.github.com/users/matheusfrancisco/following{/other_user}",
"gists_url": "https://api.github.com/users/matheusfrancisco/gists{/gist_id}",
"starred_url": "https://api.github.com/users/matheusfrancisco/starred{/owner}{/repo}",
"subscriptions_url": "https://api.github.com/users/matheusfrancisco/subscriptions",
"organizations_url": "https://api.github.com/users/matheusfrancisco/orgs",
"repos_url": "https://api.github.com/users/matheusfrancisco/repos",
"events_url": "https://api.github.com/users/matheusfrancisco/events{/privacy}",
"received_events_url": "https://api.github.com/users/matheusfrancisco/received_events",
"type": "User",
"site_admin": false,
"score": 1
},
{
"login": "MatheusR42",
"id": 16908590,
"node_id": "MDQ6VXNlcjE2OTA4NTkw",
"avatar_url": "https://avatars.githubusercontent.com/u/16908590?v=4",
"gravatar_id": "",
"url": "https://api.github.com/users/MatheusR42",
"html_url": "https://github.com/MatheusR42",
"followers_url": "https://api.github.com/users/MatheusR42/followers",
"following_url": "https://api.github.com/users/MatheusR42/following{/other_user}",
"gists_url": "https://api.github.com/users/MatheusR42/gists{/gist_id}",
"starred_url": "https://api.github.com/users/MatheusR42/starred{/owner}{/repo}",
"subscriptions_url": "https://api.github.com/users/MatheusR42/subscriptions",
"organizations_url": "https://api.github.com/users/MatheusR42/orgs",
"repos_url": "https://api.github.com/users/MatheusR42/repos",
"events_url": "https://api.github.com/users/MatheusR42/events{/privacy}",
"received_events_url": "https://api.github.com/users/MatheusR42/received_events",
"type": "User",
"site_admin": false,
"score": 1
},
{
"login": "matheusz98",
"id": 63810194,
"node_id": "MDQ6VXNlcjYzODEwMTk0",
"avatar_url": "https://avatars.githubusercontent.com/u/63810194?v=4",
"gravatar_id": "",
"url": "https://api.github.com/users/matheusz98",
"html_url": "https://github.com/matheusz98",
"followers_url": "https://api.github.com/users/matheusz98/followers",
"following_url": "https://api.github.com/users/matheusz98/following{/other_user}",
"gists_url": "https://api.github.com/users/matheusz98/gists{/gist_id}",
"starred_url": "https://api.github.com/users/matheusz98/starred{/owner}{/repo}",
"subscriptions_url": "https://api.github.com/users/matheusz98/subscriptions",
"organizations_url": "https://api.github.com/users/matheusz98/orgs",
"repos_url": "https://api.github.com/users/matheusz98/repos",
"events_url": "https://api.github.com/users/matheusz98/events{/privacy}",
"received_events_url": "https://api.github.com/users/matheusz98/received_events",
"type": "User",
"site_admin": false,
"score": 1
},
{
"login": "MatheusVict",
"id": 103688000,
"node_id": "U_kgDOBi4nQA",
"avatar_url": "https://avatars.githubusercontent.com/u/103688000?v=4",
"gravatar_id": "",
"url": "https://api.github.com/users/MatheusVict",
"html_url": "https://github.com/MatheusVict",
"followers_url": "https://api.github.com/users/MatheusVict/followers",
"following_url": "https://api.github.com/users/MatheusVict/following{/other_user}",
"gists_url": "https://api.github.com/users/MatheusVict/gists{/gist_id}",
"starred_url": "https://api.github.com/users/MatheusVict/starred{/owner}{/repo}",
"subscriptions_url": "https://api.github.com/users/MatheusVict/subscriptions",
"organizations_url": "https://api.github.com/users/MatheusVict/orgs",
"repos_url": "https://api.github.com/users/MatheusVict/repos",
"events_url": "https://api.github.com/users/MatheusVict/events{/privacy}",
"received_events_url": "https://api.github.com/users/MatheusVict/received_events",
"type": "User",
"site_admin": false,
"score": 1
},
{
"login": "MatheusRich",
"id": 20938712,
"node_id": "MDQ6VXNlcjIwOTM4NzEy",
"avatar_url": "https://avatars.githubusercontent.com/u/20938712?v=4",
"gravatar_id": "",
"url": "https://api.github.com/users/MatheusRich",
"html_url": "https://github.com/MatheusRich",
"followers_url": "https://api.github.com/users/MatheusRich/followers",
"following_url": "https://api.github.com/users/MatheusRich/following{/other_user}",
"gists_url": "https://api.github.com/users/MatheusRich/gists{/gist_id}",
"starred_url": "https://api.github.com/users/MatheusRich/starred{/owner}{/repo}",
"subscriptions_url": "https://api.github.com/users/MatheusRich/subscriptions",
"organizations_url": "https://api.github.com/users/MatheusRich/orgs",
"repos_url": "https://api.github.com/users/MatheusRich/repos",
"events_url": "https://api.github.com/users/MatheusRich/events{/privacy}",
"received_events_url": "https://api.github.com/users/MatheusRich/received_events",
"type": "User",
"site_admin": false,
"score": 1
},
{
"login": "Matheus-Garbelini",
"id": 6465668,
"node_id": "MDQ6VXNlcjY0NjU2Njg=",
"avatar_url": "https://avatars.githubusercontent.com/u/6465668?v=4",
"gravatar_id": "",
"url": "https://api.github.com/users/Matheus-Garbelini",
"html_url": "https://github.com/Matheus-Garbelini",
"followers_url": "https://api.github.com/users/Matheus-Garbelini/followers",
"following_url": "https://api.github.com/users/Matheus-Garbelini/following{/other_user}",
"gists_url": "https://api.github.com/users/Matheus-Garbelini/gists{/gist_id}",
"starred_url": "https://api.github.com/users/Matheus-Garbelini/starred{/owner}{/repo}",
"subscriptions_url": "https://api.github.com/users/Matheus-Garbelini/subscriptions",
"organizations_url": "https://api.github.com/users/Matheus-Garbelini/orgs",
"repos_url": "https://api.github.com/users/Matheus-Garbelini/repos",
"events_url": "https://api.github.com/users/Matheus-Garbelini/events{/privacy}",
"received_events_url": "https://api.github.com/users/Matheus-Garbelini/received_events",
"type": "User",
"site_admin": false,
"score": 1
},
{
"login": "matheuslc",
"id": 4161171,
"node_id": "MDQ6VXNlcjQxNjExNzE=",
"avatar_url": "https://avatars.githubusercontent.com/u/4161171?v=4",
"gravatar_id": "",
"url": "https://api.github.com/users/matheuslc",
"html_url": "https://github.com/matheuslc",
"followers_url": "https://api.github.com/users/matheuslc/followers",
"following_url": "https://api.github.com/users/matheuslc/following{/other_user}",
"gists_url": "https://api.github.com/users/matheuslc/gists{/gist_id}",
"starred_url": "https://api.github.com/users/matheuslc/starred{/owner}{/repo}",
"subscriptions_url": "https://api.github.com/users/matheuslc/subscriptions",
"organizations_url": "https://api.github.com/users/matheuslc/orgs",
"repos_url": "https://api.github.com/users/matheuslc/repos",
"events_url": "https://api.github.com/users/matheuslc/events{/privacy}",
"received_events_url": "https://api.github.com/users/matheuslc/received_events",
"type": "User",
"site_admin": false,
"score": 1
},
{
"login": "matheusd",
"id": 1752493,
"node_id": "MDQ6VXNlcjE3NTI0OTM=",
"avatar_url": "https://avatars.githubusercontent.com/u/1752493?v=4",
"gravatar_id": "",
"url": "https://api.github.com/users/matheusd",
"html_url": "https://github.com/matheusd",
"followers_url": "https://api.github.com/users/matheusd/followers",
"following_url": "https://api.github.com/users/matheusd/following{/other_user}",
"gists_url": "https://api.github.com/users/matheusd/gists{/gist_id}",
"starred_url": "https://api.github.com/users/matheusd/starred{/owner}{/repo}",
"subscriptions_url": "https://api.github.com/users/matheusd/subscriptions",
"organizations_url": "https://api.github.com/users/matheusd/orgs",
"repos_url": "https://api.github.com/users/matheusd/repos",
"events_url": "https://api.github.com/users/matheusd/events{/privacy}",
"received_events_url": "https://api.github.com/users/matheusd/received_events",
"type": "User",
"site_admin": false,
"score": 1
},
{
"login": "MatheusHonorato",
"id": 19641180,
"node_id": "MDQ6VXNlcjE5NjQxMTgw",
"avatar_url": "https://avatars.githubusercontent.com/u/19641180?v=4",
"gravatar_id": "",
"url": "https://api.github.com/users/MatheusHonorato",
"html_url": "https://github.com/MatheusHonorato",
"followers_url": "https://api.github.com/users/MatheusHonorato/followers",
"following_url": "https://api.github.com/users/MatheusHonorato/following{/other_user}",
"gists_url": "https://api.github.com/users/MatheusHonorato/gists{/gist_id}",
"starred_url": "https://api.github.com/users/MatheusHonorato/starred{/owner}{/repo}",
"subscriptions_url": "https://api.github.com/users/MatheusHonorato/subscriptions",
"organizations_url": "https://api.github.com/users/MatheusHonorato/orgs",
"repos_url": "https://api.github.com/users/MatheusHonorato/repos",
"events_url": "https://api.github.com/users/MatheusHonorato/events{/privacy}",
"received_events_url": "https://api.github.com/users/MatheusHonorato/received_events",
"type": "User",
"site_admin": false,
"score": 1
},
{
"login": "mahenrique94",
"id": 11684103,
"node_id": "MDQ6VXNlcjExNjg0MTAz",
"avatar_url": "https://avatars.githubusercontent.com/u/11684103?v=4",
"gravatar_id": "",
"url": "https://api.github.com/users/mahenrique94",
"html_url": "https://github.com/mahenrique94",
"followers_url": "https://api.github.com/users/mahenrique94/followers",
"following_url": "https://api.github.com/users/mahenrique94/following{/other_user}",
"gists_url": "https://api.github.com/users/mahenrique94/gists{/gist_id}",
"starred_url": "https://api.github.com/users/mahenrique94/starred{/owner}{/repo}",
"subscriptions_url": "https://api.github.com/users/mahenrique94/subscriptions",
"organizations_url": "https://api.github.com/users/mahenrique94/orgs",
"repos_url": "https://api.github.com/users/mahenrique94/repos",
"events_url": "https://api.github.com/users/mahenrique94/events{/privacy}",
"received_events_url": "https://api.github.com/users/mahenrique94/received_events",
"type": "User",
"site_admin": false,
"score": 1
},
{
"login": "msfidelis",
"id": 13524134,
"node_id": "MDQ6VXNlcjEzNTI0MTM0",
"avatar_url": "https://avatars.githubusercontent.com/u/13524134?v=4",
"gravatar_id": "",
"url": "https://api.github.com/users/msfidelis",
"html_url": "https://github.com/msfidelis",
"followers_url": "https://api.github.com/users/msfidelis/followers",
"following_url": "https://api.github.com/users/msfidelis/following{/other_user}",
"gists_url": "https://api.github.com/users/msfidelis/gists{/gist_id}",
"starred_url": "https://api.github.com/users/msfidelis/starred{/owner}{/repo}",
"subscriptions_url": "https://api.github.com/users/msfidelis/subscriptions",
"organizations_url": "https://api.github.com/users/msfidelis/orgs",
"repos_url": "https://api.github.com/users/msfidelis/repos",
"events_url": "https://api.github.com/users/msfidelis/events{/privacy}",
"received_events_url": "https://api.github.com/users/msfidelis/received_events",
"type": "User",
"site_admin": false,
"score": 1
},
{
"login": "matheusrcruz",
"id": 31409846,
"node_id": "MDQ6VXNlcjMxNDA5ODQ2",
"avatar_url": "https://avatars.githubusercontent.com/u/31409846?v=4",
"gravatar_id": "",
"url": "https://api.github.com/users/matheusrcruz",
"html_url": "https://github.com/matheusrcruz",
"followers_url": "https://api.github.com/users/matheusrcruz/followers",
"following_url": "https://api.github.com/users/matheusrcruz/following{/other_user}",
"gists_url": "https://api.github.com/users/matheusrcruz/gists{/gist_id}",
"starred_url": "https://api.github.com/users/matheusrcruz/starred{/owner}{/repo}",
"subscriptions_url": "https://api.github.com/users/matheusrcruz/subscriptions",
"organizations_url": "https://api.github.com/users/matheusrcruz/orgs",
"repos_url": "https://api.github.com/users/matheusrcruz/repos",
"events_url": "https://api.github.com/users/matheusrcruz/events{/privacy}",
"received_events_url": "https://api.github.com/users/matheusrcruz/received_events",
"type": "User",
"site_admin": false,
"score": 1
}
]
}
""";